name = "GeoDataPicker"
uuid = "ad26291b-5ad9-4b61-8cdb-f4ecfd1c1fc8"
authors = ["Boris Kaus <kaus@uni-mainz.de>", "Marcel Thielmann <Marcel.Thielmann@uni-bayreuth.de>"]
version = "0.1.2"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashBootstrapComponents = "1b08a953-4be3-4667-9a23-fa6d05876a1e"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UrlDownload = "856ac37a-3032-4c1c-9122-f86d88358c8b"

[compat]
Dash = "1.3.0"
DashBootstrapComponents = "1.4.1"
DelimitedFiles = "1"
GeophysicalModelGenerator = "0.5.4"
HTTP = "1.0"
JLD2 = "0.4"
JSON3 = "1"
PlotlyJS = "0.18"
Statistics = "1.9"
UrlDownload = "1.0.1"
julia = "1.9"
Meshes = "0.30"
